In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import scipy.stats as stats
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('Modelling_Customer_churn.csv')
df.head()

user_id    apm  income   height  reaction_time  age  kappa_ability  \
0    78389  154.0   100.0  176.000          353.0   47           6291   
1    79235  193.0    95.0  182.000          250.0   20           4765   
2    78816  180.0    97.0  177.000          311.0   67           4360   
3    78961  168.0    99.0  184.000          320.0   48           3663   
4    78427  207.0   105.0  190.382          329.0   35            149   

    weight  amount  gregariousness  ...  Neapolitan  Orange Sherbert  Peach  \
0  149.000      10            48.0  ...           0                0      0   
1  155.238      19            62.0  ...           0                0      0   
2  145.000      41            57.0  ...           0                0      0   
3  148.000     105            43.0  ...           0                0      1   
4  146.000      53            58.0  ...           0                0      0   

   Pistachio  Red Velvet  Rocky Road  Strawberry  Vanilla  Pause Associates  \
0          0           1           0           0        0                 1   
1          0           1           0           0        0                 0   
2          0           0           0           1        0                 1   
3          0           0           0           0        0                 1   
4          0           1           0           0        0                 1   

   Stop Inc  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 51 columns]

# Standardizing data

In [10]:
df_scaled = df.copy()

In [11]:
columns = ['user_id','apm','income','height','reaction_time','age','kappa_ability','weight','amount','gregariousness']

In [12]:
df1 = df_scaled[columns]

In [16]:
df1.head()

user_id    apm  income   height  reaction_time  age  kappa_ability  \
0    78389  154.0   100.0  176.000          353.0   47           6291   
1    79235  193.0    95.0  182.000          250.0   20           4765   
2    78816  180.0    97.0  177.000          311.0   67           4360   
3    78961  168.0    99.0  184.000          320.0   48           3663   
4    78427  207.0   105.0  190.382          329.0   35            149   

    weight  amount  gregariousness  
0  149.000      10            48.0  
1  155.238      19            62.0  
2  145.000      41            57.0  
3  148.000     105            43.0  
4  146.000      53            58.0

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [20]:
df_ss= pd.DataFrame(scaler.fit_transform(df1), columns=df1.columns)

In [21]:
df_ss.head()

user_id       apm    income    height  reaction_time       age  \
0 -1.311163 -1.332470 -0.438963 -0.340803       1.538041  0.252284   
1  1.619468  0.017340 -1.239990  1.050811      -1.732160 -1.650948   
2  0.168009 -0.432597 -0.919579 -0.108867       0.204561  1.662086   
3  0.670304 -0.847923 -0.599168  1.514682       0.490307  0.322774   
4 -1.179527  0.501887  0.362064  2.994894       0.776052 -0.593597   

   kappa_ability    weight    amount  gregariousness  
0       2.909073 -0.617619 -0.636361       -0.061828  
1       1.962708  0.319638 -0.358407        1.386543  
2       1.711543 -1.218618  0.321037        0.869267  
3       1.279291 -0.767869  2.297601       -0.579103  
4      -0.899953 -1.068368  0.691643        0.972722

In [22]:
df_ss['user_id'] = df1['user_id']

In [24]:
df_scaled.drop(columns=['apm','income','height','reaction_time','age','kappa_ability','weight','amount','gregariousness'], axis=1, inplace=True)

In [26]:
df_scaled = df_scaled.merge(df_ss, how='inner', on='user_id')

In [27]:
df_scaled.head()

user_id  account_verified  product_use  product_visit  churn  \
0    78389                 0           23             91      0   
1    79235                 7           35             44      0   
2    78816                 0            0             81      0   
3    78961                 0            0             83      0   
4    78427                 0           28             20      0   

   grade_ordinal  Bacon  Basil  Black olives  Chicken  ...  Stop Inc  \
0              3      0      0             0        0  ...         0   
1              2      0      0             0        0  ...         0   
2              3      0      0             0        0  ...         0   
3              3      0      0             1        0  ...         0   
4              1      0      0             0        0  ...         0   

        apm    income    height  reaction_time       age  kappa_ability  \
0 -1.332470 -0.438963 -0.340803       1.538041  0.252284       2.909073   
1  0.017340 -1.239990  1.050811      -1.732160 -1.650948       1.962708   
2 -0.432597 -0.919579 -0.108867       0.204561  1.662086       1.711543   
3 -0.847923 -0.599168  1.514682       0.490307  0.322774       1.279291   
4  0.501887  0.362064  2.994894       0.776052 -0.593597      -0.899953   

     weight    amount  gregariousness  
0 -0.617619 -0.636361       -0.061828  
1  0.319638 -0.358407        1.386543  
2 -1.218618  0.321037        0.869267  
3 -0.767869  2.297601       -0.579103  
4 -1.068368  0.691643        0.972722  

[5 rows x 51 columns]

In [28]:
df_scaled.drop(columns=['user_id'], axis=1, inplace=True)

In [29]:
X = df_scaled.drop(columns=['churn'], axis=1)
y = df['churn']

In [30]:
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score

In [31]:
skfold = StratifiedKFold(n_splits=5)
skfold.get_n_splits(X, y)

5

In [33]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [34]:
scores =  cross_val_score(model, X, y, cv=skfold, scoring='recall')

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

In [35]:
print(scores)

[0.96969697 0.96969697 0.93939394 0.95454545 0.98484848]


In [36]:
print(np.mean(scores))

0.9636363636363636


In [37]:
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(model, X, y, cv=skfold)
y_pred

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y,y_pred)

0.978

In [39]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y, y_pred)
cm

array([[660,  10],
       [ 12, 318]])

In [40]:
from sklearn.metrics import classification_report
print(classification_report(y, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       670
           1       0.97      0.96      0.97       330

    accuracy                           0.98      1000
   macro avg       0.98      0.97      0.98      1000
weighted avg       0.98      0.98      0.98      1000

